import json
import os

schemes_data = [
    {
        "id": 1,
        "slug": "pm-jay",
        "scheme_full_name": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        "disease / focus": "Secondary and Tertiary Hospitalization & Surgery",
        "category": "Hospitalization",
        "state": "All India",
        "income_limit": "BPL / SECC deprivation criteria (or under ₹2.5 Lakh/yr for priority households)",
        "documents_required": "Aadhaar Card, Ration Card / NFSA Card, Identity Proof",
        "application_link": "https://pmjay.gov.in",
        "short_description": "Comprehensive health insurance cover of ₹5,00,000 per family per year for secondary and tertiary care hospitalization across public and private empanelled hospitals.",
        "long_description": "Ayushman Bharat PM-JAY is the world's largest government-funded health insurance scheme. It provides a cover of ₹5 lakh per family per year for medical treatment, surgical procedures, ICU care, diagnostics, and medicines with 100% cashless and paperless access at point of service.",
        "government_department": "National Health Authority (NHA), Ministry of Health & Family Welfare",
        "scheme_type": "Central",
        "target_population": "Bottom 40% vulnerable and low-income households identified via SECC / NFSA database",
        "states_covered": "All India (Nationwide Portability)",
        "coverage_amount": "₹5,00,000 per family per year",
        "cashless": True,
        "application_process": "1. Visit the nearest PM-JAY empanelled hospital or Common Service Centre (CSC).\n2. Contact the Ayushman Mitra helpdesk.\n3. Present Aadhaar card and Ration card for biometric e-KYC verification.\n4. Receive Ayushman Bharat card and cashless admission.",
        "application_mode": "Hospital Ayushman Mitra Desk / CSC / Online Portal",
        "helpline": "14555",
        "official_website": "https://pmjay.gov.in",
        "official_source": "National Health Authority",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 1,
        "eligibility_rule": {
            "min_age": 0,
            "max_age": 120,
            "gender": "All",
            "max_annual_income": 250000,
            "bpl_required": True,
            "requires_pregnancy": False,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": True,
            "applicable_states": "All India",
            "healthcare_conditions": "Hospitalization, Surgery, ICU, Oncology, Cardiology, Orthopedics, Nephrology"
        },
        "benefits": [
            {"title": "Cashless Hospitalization", "description": "Up to ₹5 Lakhs annual family coverage across 1,900+ treatment and surgical packages.", "amount": 500000},
            {"title": "Pre & Post Hospitalization", "description": "Covers diagnostic consultations 3 days prior and medicines 15 days post-discharge.", "amount": 0},
            {"title": "Pre-existing Disease Coverage", "description": "All pre-existing medical conditions are covered from day one of enrollment.", "amount": 0}
        ],
        "documents": [
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Primary identity verification for beneficiary"},
            {"name": "Ration Card / NFSA Card", "is_mandatory": True, "description": "Proof of household inclusion under BPL/SECC deprivation criteria"}
        ]
    },
    {
        "id": 2,
        "slug": "mjpjay",
        "scheme_full_name": "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)",
        "disease / focus": "Critical Illnesses, Surgeries & Specialized Hospitalization",
        "category": "Hospitalization",
        "state": "Maharashtra",
        "income_limit": "Yellow / Orange Ration Card (or Antyodaya / Annapurna Card, all farmers in 14 distressed districts)",
        "documents_required": "Yellow / Orange Ration Card, Aadhaar Card / Voter ID, Domicile Certificate",
        "application_link": "https://www.jeevandayee.gov.in",
        "short_description": "Maharashtra flagship health assurance program providing ₹5,00,000 cashless cover across 996+ medical & surgical procedures.",
        "long_description": "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY) is the flagship health assurance scheme of the Government of Maharashtra. The scheme provides financial protection for identified secondary and tertiary hospitalization procedures in empanelled network hospitals.",
        "government_department": "State Health Assurance Society, Public Health Department, Maharashtra",
        "scheme_type": "State",
        "target_population": "Families holding Yellow, Orange, Antyodaya, or Annapurna ration cards residing in Maharashtra",
        "states_covered": "Maharashtra",
        "coverage_amount": "₹5,00,000 per family per year (₹2.5L for renal transplant)",
        "cashless": True,
        "application_process": "1. Visit an empanelled hospital in Maharashtra.\n2. Meet the Arogyamitra at the MJPJAY registration counter.\n3. Submit valid Yellow/Orange ration card and Aadhaar card.\n4. Arogyamitra generates pre-authorization request for instant cashless approval.",
        "application_mode": "Hospital Arogyamitra Desk",
        "helpline": "1800 120 8040 / 155 388",
        "official_website": "https://www.jeevandayee.gov.in",
        "official_source": "State Health Assurance Society, Maharashtra",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 2,
        "eligibility_rule": {
            "min_age": 0,
            "max_age": 120,
            "gender": "All",
            "max_annual_income": 100000,
            "bpl_required": True,
            "requires_pregnancy": False,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": True,
            "applicable_states": "Maharashtra",
            "healthcare_conditions": "Critical Illness, Surgery, Cardiology, Oncology, Polytrauma, Burns, Neurology"
        },
        "benefits": [
            {"title": "Cashless Surgical Treatment", "description": "Coverage for 996 medical and surgical procedures across 30 specialized clinical categories.", "amount": 500000},
            {"title": "Renal Transplant Cover", "description": "Specialized upper package ceiling up to ₹2.5 Lakhs for kidney transplantation.", "amount": 250000}
        ],
        "documents": [
            {"name": "Valid Yellow / Orange Ration Card", "is_mandatory": True, "description": "Proof of family socioeconomic category issued by Govt of Maharashtra"},
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Beneficiary identity verification document"}
        ]
    },
    {
        "id": 3,
        "slug": "pmmvy",
        "scheme_full_name": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        "disease / focus": "Maternal Nutrition & Conditional Cash Transfer for Pregnant Women",
        "category": "Maternal",
        "state": "All India",
        "income_limit": "Family annual income up to ₹8,00,000 / EWS / SC / ST / BPL or MGNREGA workers",
        "documents_required": "Mother Aadhaar Card, Husband Aadhaar Card, Mother-Child Protection (MCP) Card, Bank Passbook",
        "application_link": "https://pmmvy.wcd.gov.in",
        "short_description": "Direct Benefit Transfer of ₹5,000 to pregnant women for 1st child and ₹6,000 for 2nd child (if girl) for wage loss compensation and maternal nutrition.",
        "long_description": "PMMVY is a Centrally Sponsored Conditional Cash Transfer scheme for pregnant women and lactating mothers. It provides financial assistance directly to bank accounts in installments upon early registration of pregnancy, antenatal check-ups, and child immunization.",
        "government_department": "Ministry of Women and Child Development, Government of India",
        "scheme_type": "Central",
        "target_population": "Pregnant Women and Lactating Mothers (PW&LM) for first and second live births",
        "states_covered": "All India",
        "coverage_amount": "₹5,000 (1st Child) / ₹6,000 (2nd Child if Girl)",
        "cashless": False,
        "application_process": "1. Register pregnancy at nearest Anganwadi Centre (AWC) or Government Health Facility.\n2. Submit MCP Card details and bank account information.\n3. Direct Benefit Transfer (DBT) is credited in verified Aadhaar-linked bank account.",
        "application_mode": "Anganwadi Centre / PMMVY Portal (Online)",
        "helpline": "011-23382393",
        "official_website": "https://pmmvy.wcd.gov.in",
        "official_source": "Ministry of Women and Child Development",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 3,
        "eligibility_rule": {
            "min_age": 18,
            "max_age": 45,
            "gender": "Female",
            "max_annual_income": 800000,
            "bpl_required": False,
            "requires_pregnancy": True,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "All India",
            "healthcare_conditions": "Pregnancy, Antenatal Nutrition, Maternal Care"
        },
        "benefits": [
            {"title": "First Installment (₹3,000)", "description": "Paid on early pregnancy registration and at least one Antenatal Check-up (ANC) within 6 months.", "amount": 3000},
            {"title": "Second Installment (₹2,000)", "description": "Paid after child birth registration and first cycle of vaccinations (BCG, OPV, DPT, Hepatitis B).", "amount": 2000}
        ],
        "documents": [
            {"name": "Mother-Child Protection (MCP) Card", "is_mandatory": True, "description": "Official RCH tracking card issued during ANC"},
            {"name": "Aadhaar Card (Mother & Husband)", "is_mandatory": True, "description": "Identity and biometric validation"},
            {"name": "Bank Passbook", "is_mandatory": True, "description": "Aadhaar-seeded bank account details for DBT transfer"}
        ]
    },
    {
        "id": 4,
        "slug": "jsy",
        "scheme_full_name": "Janani Suraksha Yojana (JSY)",
        "disease / focus": "Safe Motherhood Intervention & Institutional Delivery",
        "category": "Maternal",
        "state": "All India",
        "income_limit": "All BPL/SC/ST pregnant women (all pregnant women in Low Performing States)",
        "documents_required": "JSY Card, MCP Card, Aadhaar Card, BPL Card, Bank Account Details",
        "application_link": "https://nhm.gov.in",
        "short_description": "Safe motherhood cash incentive of ₹1,400 (rural) / ₹1,000 (urban) promoting institutional delivery to reduce maternal and neonatal mortality.",
        "long_description": "Janani Suraksha Yojana (JSY) is a safe motherhood intervention under the National Health Mission. It links cash assistance with antenatal care and delivery in public health facilities or accredited private hospitals.",
        "government_department": "National Health Mission, Ministry of Health & Family Welfare",
        "scheme_type": "Central",
        "target_population": "Pregnant women delivering in government or accredited private healthcare institutions",
        "states_covered": "All India",
        "coverage_amount": "₹1,400 (Rural) / ₹1,000 (Urban) cash incentive",
        "cashless": False,
        "application_process": "1. Register pregnancy with local ASHA / ANM.\n2. Undergo required antenatal visits.\n3. Deliver at a public health center or accredited hospital.\n4. Cash assistance is disbursed before discharge via DBT.",
        "application_mode": "Public Health Center / ASHA Worker",
        "helpline": "104 / 108",
        "official_website": "https://nhm.gov.in",
        "official_source": "National Health Mission",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 4,
        "eligibility_rule": {
            "min_age": 19,
            "max_age": 45,
            "gender": "Female",
            "max_annual_income": 200000,
            "bpl_required": True,
            "requires_pregnancy": True,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "All India",
            "healthcare_conditions": "Pregnancy, Institutional Delivery"
        },
        "benefits": [
            {"title": "Institutional Delivery Cash Incentive", "description": "₹1,400 for rural mothers and ₹1,000 for urban mothers delivering in accredited health facilities.", "amount": 1400},
            {"title": "ASHA Package Support", "description": "Transport and tracking accompaniment provided free of cost.", "amount": 0}
        ],
        "documents": [
            {"name": "MCP Card", "is_mandatory": True, "description": "Proof of antenatal care checkups"},
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Proof of identity"},
            {"name": "BPL / Ration Card", "is_mandatory": True, "description": "Socioeconomic category proof"}
        ]
    },
    {
        "id": 5,
        "slug": "charitable-hospitals-treatment",
        "scheme_full_name": "Free & Concessional Treatment in Charitable Hospitals",
        "disease / focus": "Free Inpatient & Outpatient Care in State Charitable Trust Hospitals",
        "category": "Hospitalization",
        "state": "Maharashtra",
        "income_limit": "Free: Annual family income up to ₹85,000; Concessional (50%): Income up to ₹1,60,000",
        "documents_required": "Income Certificate from Tahsildar / Yellow/Orange Ration Card, Aadhaar Card",
        "application_link": "https://charity.maharashtra.gov.in",
        "short_description": "Statutory reservation of 10% free beds (Indigent Patients Fund - IPF) and 10% concessional beds (Weaker Section) in all registered charitable trust hospitals across Maharashtra.",
        "long_description": "Under Section 41AA of the Maharashtra Public Trusts Act and High Court Scheme, every charitable trust hospital must reserve 10% of operational beds for completely free treatment of indigent patients (annual income <= ₹85,000) and 10% at a 50% discount for weaker sections (annual income <= ₹1,60,000).",
        "government_department": "Office of the Charity Commissioner, Government of Maharashtra",
        "scheme_type": "State",
        "target_population": "Economically indigent and weaker section citizens in Maharashtra needing hospital treatment",
        "states_covered": "Maharashtra",
        "coverage_amount": "100% Free (Indigent <= ₹85K) / 50% Concessional (Weaker <= ₹1.6L)",
        "cashless": True,
        "application_process": "1. Approach Medical Social Worker (MSW) at any registered Charitable Trust Hospital.\n2. Present Tahsildar Income Certificate / BPL ration card and Aadhaar.\n3. MSW verifies documents and allocates reserved IPF free bed.",
        "application_mode": "Hospital Medical Social Worker (MSW) Desk",
        "helpline": "022-22072121",
        "official_website": "https://charity.maharashtra.gov.in",
        "official_source": "Charity Commissioner, Maharashtra",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 5,
        "eligibility_rule": {
            "min_age": 0,
            "max_age": 120,
            "gender": "All",
            "max_annual_income": 160000,
            "bpl_required": False,
            "requires_pregnancy": False,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": True,
            "applicable_states": "Maharashtra",
            "healthcare_conditions": "Inpatient Hospitalization, Surgery, Intensive Care, Diagnostic Investigations"
        },
        "benefits": [
            {"title": "100% Free Treatment (Indigent Section)", "description": "Completely free bed, nursing, medicines, surgery, and diagnostics for families with income <= ₹85,000.", "amount": 0},
            {"title": "50% Concessional Treatment (Weaker Section)", "description": "50% discount on total hospital bill for families with annual income between ₹85,001 and ₹1,60,000.", "amount": 0}
        ],
        "documents": [
            {"name": "Income Certificate from Tahsildar", "is_mandatory": True, "description": "Official proof of family income from revenue authority"},
            {"name": "Yellow or Orange Ration Card", "is_mandatory": False, "description": "Alternative proof of socioeconomic status"},
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Identity proof"}
        ]
    },
    {
        "id": 6,
        "slug": "kutumb-niyojan",
        "scheme_full_name": "Kutumb Niyojan (Family Planning Indemnity Scheme)",
        "disease / focus": "Sterilization Indemnity & Voluntary Family Planning Compensation",
        "category": "General",
        "state": "All India",
        "income_limit": "No income limit for public facilities; BPL/SC/ST priority cash incentives",
        "documents_required": "Sterilization Consent Form, Aadhaar Card, Bank Account Details",
        "application_link": "https://nhm.gov.in",
        "short_description": "Free family planning counseling, modern contraceptives, and financial compensation/insurance for voluntary sterilization.",
        "long_description": "The National Family Planning program provides universal access to high-quality voluntary family planning services, modern contraceptive choices, NSV (vasectomy), laparoscopic tubectomy, and insurance cover against surgical failure or complications under the Family Planning Indemnity Scheme (FPIS).",
        "government_department": "Ministry of Health & Family Welfare, Government of India",
        "scheme_type": "Central",
        "target_population": "Adult couples seeking voluntary family planning and birth spacing",
        "states_covered": "All India",
        "coverage_amount": "Free service + Up to ₹2,00,000 indemnity cover for surgical failure",
        "cashless": True,
        "application_process": "1. Visit Primary Health Centre (PHC), Community Health Centre (CHC), or District Hospital.\n2. Consult Family Planning counselor.\n3. Sign informed consent and undergo procedure.\n4. Receive wage compensation in bank account.",
        "application_mode": "Public Health Facilities (PHC / CHC / District Hospital)",
        "helpline": "1800 11 6555",
        "official_website": "https://nhm.gov.in",
        "official_source": "Ministry of Health & Family Welfare",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 6,
        "eligibility_rule": {
            "min_age": 18,
            "max_age": 49,
            "gender": "All",
            "max_annual_income": 0,
            "bpl_required": False,
            "requires_pregnancy": False,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "All India",
            "healthcare_conditions": "Family Planning, Sterilization, Reproductive Health"
        },
        "benefits": [
            {"title": "Free Clinical Sterilization", "description": "100% free surgical sterilization (NSV / Tubectomy) at government hospitals.", "amount": 0},
            {"title": "Wage Loss Compensation", "description": "Direct cash incentive of ₹1,000 to ₹3,000 depending on procedure type and category.", "amount": 2000},
            {"title": "Insurance Cover", "description": "Up to ₹2,00,000 cover in case of sterilization failure requiring recanalization.", "amount": 200000}
        ],
        "documents": [
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Beneficiary identification"},
            {"name": "Bank Passbook", "is_mandatory": True, "description": "For direct compensation credit"}
        ]
    },
    {
        "id": 7,
        "slug": "jssk",
        "scheme_full_name": "Janani Shishu Suraksha Karyakram (JSSK)",
        "disease / focus": "Zero Out-of-Pocket Delivery & Sick Newborn Healthcare",
        "category": "Maternal",
        "state": "All India",
        "income_limit": "Zero Income Restriction (Universal for all pregnant women & sick infants)",
        "documents_required": "MCP Card, Aadhaar Card / Identity Proof",
        "application_link": "https://nhm.gov.in",
        "short_description": "Completely free, cashless delivery (including C-section), free drugs, diagnostics, blood, food, and transport for pregnant women and sick infants up to 1 year.",
        "long_description": "Janani Shishu Suraksha Karyakram (JSSK) entitles all pregnant women delivering in public health institutions to absolutely free and zero out-of-pocket expenses for delivery, C-section, medicines, diagnostics, food during stay, and free transport from home to facility and drop-back.",
        "government_department": "National Health Mission, Ministry of Health & Family Welfare",
        "scheme_type": "Central",
        "target_population": "All pregnant women delivering in public facilities and all sick newborns/infants up to 1 year",
        "states_covered": "All India",
        "coverage_amount": "100% Free & Cashless (Zero Out-of-Pocket Expense)",
        "cashless": True,
        "application_process": "1. Arrive at any Government Hospital (PHC, CHC, Sub-District, District Hospital, Medical College).\n2. Present MCP Card / ID.\n3. Receive 100% free delivery care, free diagnostics, medicines, and free ambulance transport.",
        "application_mode": "Direct Admission at Public Health Institutions",
        "helpline": "102 / 108",
        "official_website": "https://nhm.gov.in",
        "official_source": "National Health Mission",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 7,
        "eligibility_rule": {
            "min_age": 15,
            "max_age": 50,
            "gender": "Female",
            "max_annual_income": 0,
            "bpl_required": False,
            "requires_pregnancy": True,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": True,
            "applicable_states": "All India",
            "healthcare_conditions": "Normal Delivery, Cesarean Section, Maternal Complications, Neonatal Care"
        },
        "benefits": [
            {"title": "Zero Out-of-Pocket Delivery", "description": "Free and cashless delivery including emergency Caesarean Section surgery.", "amount": 0},
            {"title": "Free Drugs and Consumables", "description": "All essential medicines, IV fluids, and surgical supplies provided without charge.", "amount": 0},
            {"title": "Free Diet during Stay", "description": "Free wholesome meals up to 3 days for normal delivery and 7 days for C-section.", "amount": 0},
            {"title": "Free Transport (102/108)", "description": "Free ambulance from home to facility, inter-facility transfer, and drop back home.", "amount": 0}
        ],
        "documents": [
            {"name": "Mother-Child Protection (MCP) Card", "is_mandatory": False, "description": "Antenatal tracking card (recommended, but emergency care is never denied without it)"},
            {"name": "Aadhaar Card", "is_mandatory": False, "description": "Identity verification"}
        ]
    },
    {
        "id": 8,
        "slug": "vatsalya-mata-bal",
        "scheme_full_name": "Vatsalya - Mata va Bal Arogya Abhiyan",
        "disease / focus": "High-Risk Pregnancy Tracking & Maternal-Child Nutrition",
        "category": "Maternal",
        "state": "Maharashtra",
        "income_limit": "Universal in Maharashtra with priority for rural/tribal pregnant women",
        "documents_required": "MCP Card, Aadhaar Card, Resident Domicile Proof",
        "application_link": "https://arogya.maharashtra.gov.in",
        "short_description": "Maharashtra state initiative for intensive identification, specialized monitoring, and clinical management of High-Risk Pregnancies (HRP) and malnourished children.",
        "long_description": "Vatsalya Mata va Bal Arogya is a targeted mission under the Public Health Department of Maharashtra focusing on intensive screening of severe anemia, gestational diabetes, hypertension (preeclampsia), and institutional referral protocols to reduce maternal and infant mortality rates.",
        "government_department": "Public Health Department, Government of Maharashtra",
        "scheme_type": "State",
        "target_population": "High-risk pregnant mothers and malnourished children (SAM/MAM) in Maharashtra",
        "states_covered": "Maharashtra",
        "coverage_amount": "Free High-Risk Antenatal Care & Nutrition Kits",
        "cashless": True,
        "application_process": "1. Attend monthly village health nutrition days (VHND) or PHC antenatal clinic.\n2. Medical Officer identifies high-risk markers.\n3. Beneficiary is tagged for institutional hospital birth with dedicated transport and nutrition support.",
        "application_mode": "Primary Health Centre / District Hospital ANC Clinic",
        "helpline": "104",
        "official_website": "https://arogya.maharashtra.gov.in",
        "official_source": "Public Health Department, Maharashtra",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 8,
        "eligibility_rule": {
            "min_age": 18,
            "max_age": 45,
            "gender": "Female",
            "max_annual_income": 300000,
            "bpl_required": False,
            "requires_pregnancy": True,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "Maharashtra",
            "healthcare_conditions": "High Risk Pregnancy, Severe Anemia, Gestational Diabetes, Hypertension"
        },
        "benefits": [
            {"title": "Specialized High-Risk ANC", "description": "Free ultrasonography (USG), blood investigations, and gynecologist consultation.", "amount": 0},
            {"title": "Maternal Nutrition Kit", "description": "Iron-folic acid supplements, calcium, and specialized protein nutrition kits.", "amount": 0}
        ],
        "documents": [
            {"name": "MCP Card", "is_mandatory": True, "description": "Mother-Child Protection Card"},
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Identity proof"}
        ]
    },
    {
        "id": 9,
        "slug": "pmsma",
        "scheme_full_name": "Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)",
        "disease / focus": "Assured Antenatal Checkups on 9th of Every Month",
        "category": "Maternal",
        "state": "All India",
        "income_limit": "Universal (All pregnant women in 2nd and 3rd trimesters)",
        "documents_required": "MCP Card, Aadhaar Card / Voter ID",
        "application_link": "https://pmsma.nhp.gov.in",
        "short_description": "Guaranteed comprehensive, free-of-cost antenatal checkups on the 9th of every month conducted by Obstetricians/Gynecologists at designated public health centers.",
        "long_description": "PMSMA guarantees comprehensive, quality antenatal care to all pregnant women on the 9th of every month. It aims to identify high-risk pregnancies and ensure timely clinical intervention by specialist doctors.",
        "government_department": "Ministry of Health & Family Welfare, Government of India",
        "scheme_type": "Central",
        "target_population": "All pregnant women in their 2nd and 3rd trimesters",
        "states_covered": "All India",
        "coverage_amount": "Free Specialist Consultations & Diagnostics",
        "cashless": True,
        "application_process": "1. Visit any designated public health center or district hospital on the 9th of any month.\n2. Present your MCP Card.\n3. Undergo free ultrasound, blood/urine screening, and specialist doctor consultation.",
        "application_mode": "Designated PMSMA Clinics (9th of each month)",
        "helpline": "1800 11 6555",
        "official_website": "https://pmsma.nhp.gov.in",
        "official_source": "Ministry of Health & Family Welfare",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 9,
        "eligibility_rule": {
            "min_age": 18,
            "max_age": 45,
            "gender": "Female",
            "max_annual_income": 0,
            "bpl_required": False,
            "requires_pregnancy": True,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "All India",
            "healthcare_conditions": "Antenatal Care, High-Risk Pregnancy Screening, Ultrasound"
        },
        "benefits": [
            {"title": "Free Specialist Gynecologist Care", "description": "Comprehensive physical checkup, obstetric examination, and ultrasound.", "amount": 0},
            {"title": "Free Laboratory Investigations", "description": "Hemoglobin, blood sugar, urine albumin, HIV, syphilis, and blood grouping.", "amount": 0}
        ],
        "documents": [
            {"name": "MCP Card", "is_mandatory": True, "description": "Mother-Child Protection Card for tracking checkup history"},
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Identity verification"}
        ]
    },
    {
        "id": 10,
        "slug": "rbsk",
        "scheme_full_name": "Rashtriya Bal Swasthya Karyakram (RBSK)",
        "disease / focus": "Child Health Screening & Early Intervention for 4Ds",
        "category": "Child",
        "state": "All India",
        "income_limit": "Universal for all children aged 0 to 18 years enrolled in Anganwadi / Govt Schools",
        "documents_required": "Aadhaar Card of Child / Parent, School / Anganwadi ID",
        "application_link": "https://rbsk.gov.in",
        "short_description": "Early identification and free surgical treatment for 30+ health conditions covering the 4Ds: Defects at birth, Deficiencies, Diseases, and Developmental delays in children aged 0–18.",
        "long_description": "RBSK is an innovative child health screening initiative covering children from birth to 18 years. Mobile Health Teams screen children at Anganwadi centres and Government schools, referring those needing complex surgeries (e.g. Congenital Heart Disease, Cleft Lip/Palate, Club foot) for completely free treatment at District Early Intervention Centres (DEIC) and tertiary hospitals.",
        "government_department": "Ministry of Health & Family Welfare, Government of India",
        "scheme_type": "Central",
        "target_population": "Children from birth up to 18 years (0 to 216 months) across India",
        "states_covered": "All India",
        "coverage_amount": "100% Free Specialized Pediatric Surgery & Therapy",
        "cashless": True,
        "application_process": "1. Mobile Health Teams visit Anganwadi and Government schools for annual health screening.\n2. Detected conditions are referred to District Early Intervention Centre (DEIC).\n3. Children requiring surgery are sent to empanelled tertiary hospitals with 100% cashless coverage.",
        "application_mode": "Anganwadi / School Health Screening / DEIC Desk",
        "helpline": "104",
        "official_website": "https://rbsk.gov.in",
        "official_source": "National Health Mission",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 10,
        "eligibility_rule": {
            "min_age": 0,
            "max_age": 18,
            "gender": "All",
            "max_annual_income": 0,
            "bpl_required": False,
            "requires_pregnancy": False,
            "requires_child": True,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": True,
            "applicable_states": "All India",
            "healthcare_conditions": "Pediatric Congenital Defects, Cleft Lip, Heart Defect, Club Foot, Stunting, Autism, Hearing Impairment"
        },
        "benefits": [
            {"title": "Free Pediatric Surgeries", "description": "Free surgical correction for congenital heart defects, neural tube defects, cleft lip/palate.", "amount": 0},
            {"title": "DEIC Rehabilitation & Therapy", "description": "Free speech therapy, occupational therapy, and physiotherapy at District Early Intervention Centres.", "amount": 0}
        ],
        "documents": [
            {"name": "School / Anganwadi Registration", "is_mandatory": True, "description": "Enrollment record in government educational center"},
            {"name": "Aadhaar Card", "is_mandatory": False, "description": "Identity of parent or child"}
        ]
    },
    {
        "id": 11,
        "slug": "abdm-abha",
        "scheme_full_name": "Ayushman Bharat Health Account (ABHA / ABDM)",
        "disease / focus": "Digital Health ID & Unified Consent-Based Electronic Health Records",
        "category": "General",
        "state": "All India",
        "income_limit": "Zero Income Limit (Universal for all Indian citizens)",
        "documents_required": "Aadhaar Card / Mobile Number / Driving License",
        "application_link": "https://healthid.ndhm.gov.in",
        "short_description": "14-digit unique Digital Health ID enabling citizens to seamlessly share electronic medical records, lab reports, and prescriptions with doctors across India.",
        "long_description": "ABDM aims to develop the digital backbone for integrated digital health infrastructure in India. Creating an ABHA card gives every citizen unified digital access to verified hospital records, lab test reports, and telehealth prescriptions.",
        "government_department": "National Health Authority (NHA)",
        "scheme_type": "Central",
        "target_population": "All Indian Citizens (Universal)",
        "states_covered": "All India",
        "coverage_amount": "Free Digital Health ID & Record Interoperability",
        "cashless": True,
        "application_process": "1. Visit the official ABHA website or ABHA app.\n2. Enter Aadhaar number or mobile number.\n3. Verify via OTP.\n4. Instantly download your 14-digit ABHA card.",
        "application_mode": "Online (ABHA Portal / App) / Hospital Desk",
        "helpline": "1800 11 4477",
        "official_website": "https://healthid.ndhm.gov.in",
        "official_source": "National Health Authority",
        "verification_status": "source_provided",
        "source_file": "Pasted markdown.md",
        "source_record_id": 11,
        "eligibility_rule": {
            "min_age": 0,
            "max_age": 120,
            "gender": "All",
            "max_annual_income": 0,
            "bpl_required": False,
            "requires_pregnancy": False,
            "requires_child": False,
            "requires_disability": False,
            "requires_senior": False,
            "requires_hospitalization": False,
            "applicable_states": "All India",
            "healthcare_conditions": "Digital Health Records, OPD, Lab Reports, Prescriptions"
        },
        "benefits": [
            {"title": "Unique 14-digit Health Identifier", "description": "Unified digital identification across all empanelled hospitals, clinics, and diagnostic labs.", "amount": 0},
            {"title": "Paperless Medical Records", "description": "Instant consent-based sharing of discharge summaries, prescriptions, and lab tests.", "amount": 0}
        ],
        "documents": [
            {"name": "Aadhaar Card", "is_mandatory": True, "description": "Used for OTP-based instant e-KYC generation"}
        ]
    }
]

with open('backend/data/schemes.json', 'w', encoding='utf-8') as f:
    json.dump({'schemes': schemes_data}, f, indent=2, ensure_ascii=False)

print(f"Created backend/data/schemes.json with {len(schemes_data)} detailed real scheme records.")
